name: basic-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:2

      - name: Install dependencies
        run: composer update

      - name: Run check coding conventions
        run: composer test

      # run the action to install MediaWiki, PHP, Composer
      # and run PHPUnit tests for the extension
      - run: echo "Current status for php dependencies and other tests - ${{ job.status }}."
      - name: Mediawiki PHPUnit
        uses: wikiteq/mediawiki-phpunit-action@v2
        with:
          php: 7.4
          extension: Checklists
          testgroup: extension-Checklists

